# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14a5630813f2ec17d6622b5b0a3e211d2947f0f03c9019d1b0a2fa2c9b96a6f2ac8c613aca3ba7198822a2f2d82d384546f1c1e25c77c11cac6b28db54adc7b6

test:
  secret_key_base: be0e125bdac2966d8e4ad376a2a7babf4886a1810b727d78491cc8b0dcdb62d8a07ef701cc22bf2c896f85e9d01e2f096aaa46a4e54bae4bd6af4a054fdedd5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
